### PR TITLE
Improve Spanish localization

### PR DESCRIPTION
**Pull request by GuilleX7**
Hi! I'm a native Spanish speaker. I've tried to improve the existing AI-generated Spanish translation. Some feats:

- Fixed many errors (mainly using verbs instead of nouns/gerund for buttons/actions, nonsensical sentences, etc)
- Tried to unify some terms, such as "file", "folder", "two factor", etc, using a single term in Spanish instead of using synonyms across different sentences (which I think can mislead users)
- Improved the wording when possible: prefer active sentences instead of passive to make them sound more natural to Spanish speakers
- Localized links when possible (there's one to the IETF's RFC that I had to leave as is, since I don't think there's a translation for that)
- Localized any non-localized English/German term that I came across
- Changed all sentences to informal second person: we have two registers for "you" in Spanish (see https://www.thespanishexperiment.com/learn-spanish/formal-informal). I mostly found a mix of formal and informal in the current translation. Although formal might sometimes sound "too formal", I think it would make sense for a security application to use formal you to address to the user. I just made everything informal cause it sounds closer to the user, but I don't mind changing it (or having two different translations?)

I've tried to go one by one, matching every key with the corresponding screen in the application to understand the context, but it's been impossible for some of them -I just didn't know how to get to the corresponding screens- so I'll need some help to further improve the translation (`SettingsPageSaveIsPossibleTip.Title` sounds quite confusing to me!)

Some keys might have been modified too much (made shorter or longer, removed/introduced terms) in an attempt to make them more meaningful, but since I understand that this is not always the way to go, I'll accept any comment, always open to discuss :)

I haven't had time to update the Markdown file. I'm not even sure if it's automatically generated by some tool or not.

Thanks for this excellent application!

### CODE REVIEW

**Comment by jp-weber** [comment]
Thank you very much for your effort, I will take the time in a few days and review & merge the change. 

The markdown file is generated automatically and can be ignored. the file will be updated by me after the merge.

**Comment by jp-weber** [comment]
Some keys like ``SettingsPageSaveIsPossibleTip`` are outdated and have now been deleted locally, I'll finish the review in the next few days, but so far, longer additions in the translation are not too long in the overview 🚀

**Comment by GuilleX7** [comment]
Oh, thanks for the heads-up! I will rebase my PR and do another quick review tomorrow. Since it's been a while already, I can re-read the translations and be completely sure they don't sound weird :)

**Comment by GuilleX7** [comment]
I've updated my PR and changed 4 keys:

- ChangeDatafilePasswordContentDialogIntroText.Text: Added an "s" to match the informal register that is used in others keys
- AddAccountContentDialogNoCamPermission.Text: The original translation was understandable, but _"No se ha concedido permiso para utilizar la cámara."_ refers to _"permiso"_ (permission/consent), which is used in others translations. Also, sounds better in general because it's a direct translation of _"No permission has been granted to use the camera."_
- TutorialContentDialogHowTheAppWorks.Text: There's a big change here. While the original text was closer to the English version, a direct translation in Spanish didn't sound too straightforward because it was so passive. Apart from that, I there was a typo in the original translation (almacena**n** - the n was missing). The new translation has switched to an active voice, mentioning who stores the keys (the application - 2fast). Also, "setup keys for the various services" has been translated as "internal keys that are used to configure credential services", which I think will help users understand that we're not refering to the user's password, but some internal ones that they probably haven't even seen (if they used a QR)
- CategoryFilterFlyoutCategoriesInfo.Text: The change is simple, categories contain services, not the other way around. The original translation said "The search will return **results that contain** any of the chosen categories.", which now has been changed to "The search will return **results that belong** to any of the chosen categories."

Hope it's clear! Feel free to discard/discuss any of the changes

**Review by jp-weber — APPROVED** [review]
Looks good to me. Thank you very much for your great work 🚀

**Pull request merged**
